### PR TITLE
SR sample can take input folder

### PR DESCRIPTION
**Pull request by notecola**
Change SR sample to take folder as input and process all images.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Your code has a large amount of duplication with the existing code, and is very inefficient because it builds a predictor for each image. Therefore it cannot be accepted.

**Comment by ppwwyyxx** [comment]
Do you still wish to add this functionality?

It's easier to just modify on top of the existing `apply` function. Make it take a list of `lowres` instead of a single one, and evaluate them one by one. Python's argparse can take a list of arguments. This way the usage of the script for single / multiple images will also be compatible.

**Comment by notecola** [comment]
Hi @ppwwyyxx thanks for your response. But what about the Model(...) constructed every time for each image with the image original resolution? Is there any way to have it initialized once?

**Comment by notecola** [comment]
This would work if all input images have the same size. In other words, LR_SIZE_H and LR_SIZE_W are different for each input image.

**Comment by ppwwyyxx** [comment]
Then you'll need to modify the model to support arbitrary size (i.e. None size)

**Pull request closed without merging**
